// Code generated by generate-data. DO NOT EDIT.

package data

func init() {
	Languages["so"] = map[string]struct{}{
		"aad":       {},
		"albaabkii": {},
		"atabo":     {},
		"ay":        {},
		"ayaa":      {},
		"ayee":      {},
		"ayuu":      {},
		"dhan":      {},
		"hadana":    {},
		"in":        {},
		"inuu":      {},
		"isku":      {},
		"jiray":     {},
		"jirtay":    {},
		"ka":        {},
		"kale":      {},
		"kasoo":     {},
		"ku":        {},
		"kuu":       {},
		"lakin":     {},
		"markii":    {},
		"oo":        {},
		"si":        {},
		"soo":       {},
		"uga":       {},
		"ugu":       {},
		"uu":        {},
		"waa":       {},
		"waxa":      {},
		"waxuu":     {},
	}
}
