// Code generated by generate-data. DO NOT EDIT.

package data

func init() {
	Languages["zu"] = map[string]struct{}{
		"futhi":       {},
		"kahle":       {},
		"kakhulu":     {},
		"kanye":       {},
		"khona":       {},
		"kodwa":       {},
		"kungani":     {},
		"kusho":       {},
		"la":          {},
		"lakhe":       {},
		"lapho":       {},
		"mina":        {},
		"ngesikhathi": {},
		"nje":         {},
		"phansi":      {},
		"phezulu":     {},
		"u":           {},
		"ukuba":       {},
		"ukuthi":      {},
		"ukuze":       {},
		"uma":         {},
		"wahamba":     {},
		"wakhe":       {},
		"wami":        {},
		"wase":        {},
		"wathi":       {},
		"yakhe":       {},
		"zakhe":       {},
		"zonke":       {},
	}
}
